; Conformance config: validate purv (DUT) against Sail (reference).

[RISCOF]
ReferencePlugin=sail_cSim
ReferencePluginPath=./sail_cSim
DUTPlugin=purv
DUTPluginPath=./plugin-purv

[purv]
pluginpath=./plugin-purv
ispec=./plugin-purv/purv_isa.yaml
pspec=./plugin-purv/purv_platform.yaml
target_run=1

[sail_cSim]
pluginpath=./sail_cSim
