#!/usr/bin/env python3
"""Generate purg.c: the whole RISC-V engine as one hidden implementation file.

This is the historical, machine-distilled engine (purg = "generated"); the
checked-in purv.c is now hand-written and is what the build uses. purg is kept
regenerable as a reference for how the upstream engine was flattened.

atoom ships header-only (~45 self-guarded headers of static-inline code). A
normal C library hides all of that. This emits a single purg.c that:

  - #includes the slim public header purg.h (opaque state + public prototypes);
  - contains every internal type and the RiscvEmulatorState struct definition
    (the public typedef is an opaque tag, completed only here);
  - contains every instruction-execution body as a plain `static` function (no
    `inline` sprawl, smaller code);
  - exports just the public API (Init/Loop/Create/Destroy + accessors).

Generated by evaluating the baked RVE_E_* flags while inlining, so disabled
extensions (A, B/Zb*) and the RVE_E_HOOK instrumentation are stripped out.

  usage: flatten.py <atoom/include> <out_dir>      (writes <out_dir>/purg.c)
"""
import os, re, sys

INC = sys.argv[1]
OUTDIR = sys.argv[2]

MACROS = {
    "RVE_E_M": 1, "RVE_E_C": 1, "RVE_E_ZICSR": 1, "RVE_E_ZIFENCEI": 1,
    "RVE_E_A": 0, "RVE_E_B": 0,
    "RVE_E_ZBA": 0, "RVE_E_ZBB": 0, "RVE_E_ZBC": 0, "RVE_E_ZBS": 0,
    "RVE_E_HOOK": 0,
}

# RAM_ORIGIN is declared in the public header (the host needs it); don't redefine.
HEADER_DEFINES = {"RAM_ORIGIN"}

inc_re    = re.compile(r'^\s*#\s*include\s+["<](RiscvEmulator[^">]+)[">]')
sysinc_re = re.compile(r'^\s*#\s*include\s+<([^>]+)>')
if_re     = re.compile(r'^\s*#\s*if\s+(.*)')
ifdef_re  = re.compile(r'^\s*#\s*ifdef\s+(\w+)')
ifndef_re = re.compile(r'^\s*#\s*ifndef\s+(\w+)')
elif_re   = re.compile(r'^\s*#\s*elif\s+(.*)')
else_re   = re.compile(r'^\s*#\s*else\b')
endif_re  = re.compile(r'^\s*#\s*endif\b')
define_re = re.compile(r'^\s*#\s*define\s+(\w+)(?:\s+(\S+))?')

def evaluate(expr):
    expr = expr.split("//")[0].split("/*")[0]
    expr = expr.replace("&&", " and ").replace("||", " or ")
    expr = re.sub(r'[A-Za-z_]\w*',
                  lambda m: m.group(0) if m.group(0) in ("and", "or", "not")
                  else str(MACROS.get(m.group(0), 0)), expr)
    try:
        return bool(eval(expr, {"__builtins__": {}}, {}))
    except Exception as e:
        raise SystemExit(f"cannot evaluate #if {expr!r}: {e}")

def strip_copyright(text):
    return re.sub(r'^\s*/\*.*?\*/\s*', '', text, count=1, flags=re.S)

def inline(name, out, visited):
    if name in visited:
        return
    visited.add(name)
    with open(os.path.join(INC, name)) as f:
        text = strip_copyright(f.read())
    out.append(f"/* ===== {name} ===== */")
    stack, taken = [], []
    active = lambda: all(stack)
    for line in text.splitlines():
        m = if_re.match(line) or ifdef_re.match(line) or ifndef_re.match(line)
        if m:
            if if_re.match(line):
                val = evaluate(if_re.match(line).group(1)) if active() else False
            elif ifdef_re.match(line):
                val = (ifdef_re.match(line).group(1) in MACROS) if active() else False
            else:
                val = (ifndef_re.match(line).group(1) not in MACROS) if active() else False
            taken.append(val); stack.append(val); continue
        if elif_re.match(line):
            parent = all(stack[:-1])
            val = parent and not taken[-1] and evaluate(elif_re.match(line).group(1))
            stack[-1] = val; taken[-1] = taken[-1] or val; continue
        if else_re.match(line):
            stack[-1] = all(stack[:-1]) and not taken[-1]; continue
        if endif_re.match(line):
            if stack: stack.pop(); taken.pop()
            continue
        if not active():
            continue
        mi = inc_re.match(line)
        if mi:
            inline(mi.group(1), out, visited); continue
        if sysinc_re.match(line):
            continue
        md = define_re.match(line)
        if md:
            name2, val = md.group(1), md.group(2)
            if val is not None:
                try: MACROS[name2] = int(val, 0)
                except ValueError: pass
            if name2.endswith("_H_") or name2.startswith("RVE_E_") or name2 in HEADER_DEFINES:
                continue
        out.append(line)

BANNER = """\
/*
 * purg.c - RISC-V (RV32IMC + Zicsr/Zifencei) emulator: implementation (generated).
 *
 * Generated from atoomnetmarc/RISC-V-emulator (Apache-2.0, (c) Marc Ketel),
 * pinned commit 633526d4, by tools/flatten.py. Everything below is internal:
 * the only public surface is purg.h. Do not edit by hand; run `make regen`.
 * (The hand-written engine the build uses is purv.c/purv.h, not this file.)
 */
#include <stdint.h>
#include <string.h>
#include <stdlib.h>

#include "purg.h"

/* The engine threads a hook-context pointer through many helpers; with
 * RVE_E_HOOK baked off it is unused. Scope the warning away for this generated
 * file (mirrors upstream's own pragma around RiscvEmulatorHook). */
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wunused-parameter"
"""

# Public accessors / lifecycle: the bridge between the opaque public type and
# the internal struct. Appended after the engine so the struct is complete.
GLUE = """\

/* ------------------------------------------------------------ public API glue */

RiscvEmulatorState_t *RiscvEmulatorCreate(uint32_t initial_sp) {
    RiscvEmulatorState_t *state = calloc(1, sizeof *state);
    if (state) RiscvEmulatorInit(state, initial_sp);
    return state;
}
void RiscvEmulatorDestroy(RiscvEmulatorState_t *state) { free(state); }

uint32_t RiscvEmulatorGetRegister(const RiscvEmulatorState_t *state, int index) {
    return state->reg.x[index & 31];
}
void RiscvEmulatorSetRegister(RiscvEmulatorState_t *state, int index, uint32_t value) {
    index &= 31;
    if (index) state->reg.x[index] = value;   /* x0 stays hard-wired zero */
}
uint32_t RiscvEmulatorGetProgramCounter(const RiscvEmulatorState_t *state) {
    return state->programcounter;
}
uint32_t RiscvEmulatorGetNextProgramCounter(const RiscvEmulatorState_t *state) {
    return state->programcounternext;
}
void RiscvEmulatorSetProgramCounter(RiscvEmulatorState_t *state, uint32_t pc) {
    state->programcounter = pc;
    state->programcounternext = pc;
}
uint32_t RiscvEmulatorGetInstruction(const RiscvEmulatorState_t *state) {
    return state->instruction.value;
}
uint16_t RiscvEmulatorGetCsrNumber(const RiscvEmulatorState_t *state) {
    return state->instruction.itypecsr.csr;
}
uint32_t RiscvEmulatorGetTrapVectorBase(const RiscvEmulatorState_t *state) {
    return state->csr.mtvec.base;
}
void RiscvEmulatorRaiseIllegalInstruction(RiscvEmulatorState_t *state) {
    state->trapflag.illegalinstruction = 1;
}
"""

out = [BANNER]
# Skip Hook.h: its only content is the weak RVE_E_HOOK function, unused here.
visited = {"RiscvEmulatorConfig.h", "RiscvEmulatorImplementationSpecific.h",
           "RiscvEmulatorHook.h"}
inline("RiscvEmulatorType.h", out, visited)      # all internal types
inline("RiscvEmulatorTypeHook.h", out, visited)  # hook-context type (in signatures)
inline("RiscvEmulatorDefine.h", out, visited)    # decode macros + origins
inline("RiscvEmulatorExtension.h", out, visited) # instruction bodies
inline("RiscvEmulatorTrap.h", out, visited)
inline("RiscvEmulator.h", out, visited)          # Init/Loop
out.append("")
out.append("#pragma GCC diagnostic pop")
out.append(GLUE)

text = re.sub(r'\n{3,}', '\n\n', "\n".join(out) + "\n")

# Complete the opaque public type: turn atoom's anonymous state typedef into a
# tagged struct matching `typedef struct RiscvEmulatorState ...;` in purg.h.
text, n = re.subn(r'typedef struct\s*\{(.*?)\}\s*RiscvEmulatorState_t;',
                  r'struct RiscvEmulatorState {\1};', text, flags=re.S)
assert n == 1, f"expected exactly one RiscvEmulatorState typedef, found {n}"

# Plain functions, not static-inline (smaller code, normal style). Init/Loop are
# public (external linkage) so the host can call them.
text = text.replace("static inline ", "static ")
text = text.replace("static void RiscvEmulatorInit(", "void RiscvEmulatorInit(")
text = text.replace("static void RiscvEmulatorLoop(", "void RiscvEmulatorLoop(")

# Upstream's Init takes a "ram_length" and sets sp to RAM_ORIGIN + that, baking
# the host's RAM layout into the engine. Rename the parameter to initial_sp and
# set sp to it directly: the engine has no business knowing the RAM size, it just
# needs where the stack starts. The host now passes the absolute sp it wants.
text = text.replace("uint32_t ram_length)", "uint32_t initial_sp)")
text = text.replace("state->reg.sp = RAM_ORIGIN + ram_length;", "state->reg.sp = initial_sp;")

with open(os.path.join(OUTDIR, "purg.c"), "w") as f:
    f.write(text)
print("wrote purg.c:", text.count("\n"), "lines")
allh = {f for f in os.listdir(INC) if f.endswith(".h")}
print("not inlined:", sorted(allh - visited))
